site_name: Flow Project Dev Documentation
repo_url: https://github.com/l0rn0r/flow-dev
nav:
  - Home: index.md
  - How-To: howto.md
  - Templates: templates.md

theme: 
  name: readthedocs
  features:
    - toc.integrate